### ISSUE TITLE
[MVP] 타이틀 로고 변경

### ISSUE THREAD

**Issue by kimsanghoon1** [TheOpenCloudEngine/event-storming-tool#2]
-로고영역의 'uEngine' 텍스트를 'Eventstorming2Code' 로 변경
-Eventstorming2Code 를 형상화한 이미지 제작 후 대체
-by uengine.rog

**Comment by acmexii** [comment]
- 로고영역의 'uEngine' 텍스트를 'Eventstorming2Code' 로 변경
- Eventstorming2Code 를 형상화한 이미지 제작 후 대체

**Comment by kimsanghoon1** [comment]
임시로 제작하여 넣어둠.

**Comment by kimsanghoon1** [comment]
![image](https://user-images.githubusercontent.com/16382067/67259732-62d5d080-f4d2-11e9-8f3e-4073cd6f2278.png)
