### ISSUE TITLE
[개선] entity 를 적을시 UX 관점

### ISSUE THREAD

**Issue by kimscott** [TheOpenCloudEngine/event-storming-tool#24]
이벤트나 어그리게이트에서 id 나 name 같은 세부 항목을 적을때 'ENTITY ADD' 라는 버튼을 클릭하여 추가를 하는데,
그냥 컬럼명만 적고 엔터를 치면 자동으로 넘어가면 빠르게 작업이 될듯함.
왼쪽에 int, string 같은게 선택되어있으면 그거를 쓰고, 선택안하면 자동으로 string 으로 체크되어서..

우선순위는 낮음

**Comment by kimsanghoon1** [comment]
처리함
