### ISSUE TITLE
[개선] 코드 view 에 스크롤바 개선

### ISSUE THREAD

**Issue by kimscott** [TheOpenCloudEngine/event-storming-tool#28]
코드를 보는 화면에..
왼쪽에 트리구조와, 오른쪽에 코드를 보는것이 현재는 하나의 스크롤에 묶여서 움직이는데,
이것을 따로따로 움직이면, 코드를 볼때 현재 파일명을 확인 할 수 있어서 좋을듯함

**Comment by kimsanghoon1** [comment]
modal의 문제로, 우선 modal 크기를 auto로 주어서 폴더가 모두 닫히면 작아지는 현상이 있지만, 열었을때 스크롤은 정상적으로 생성됨
